import Header from "./components/header/Header";

import "./globals.css";
import { Roboto } from "next/font/google";

<link
    rel="shortcut icon"
    href="https://xzect.com/assets/images/xzect-logo.svg"
/>

const roboto = Roboto({
    weight: "400",
    subsets: ["latin"],
    display: "swap",
});
export const metadata = {
    title: "Xzect-Revolutionizing Technology",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <Header />

                {children}
            </body>
        </html>
    );
}
